da=read.table("http://faculty.chicagobooth.edu/ruey.tsay/teaching/introTS/d-pg-0111.txt",header=T)
head(da)
lrt=log(da$rtn+1)
acf(lrt,lag=12)
pacf(lrt,lag=12)
Box.test(lrt,lag=12,type='Ljung')
m1=arima(lrt,order=c(2,0,0),include.mean=F)
m1
tsdiag(m1,gof=12)
r1=m1$residuals
x1=100*r1
y1=x1-mean(x1)
Box.test(y1^2,lag=12,type='Ljung')
source("http://faculty.chicagobooth.edu/ruey.tsay/teaching/introTS/Egarch.R")
m2=Egarch(x1)
stresi=m2$residuals/m2$volatility
Box.test(stresi,lag=12,type='Ljung')
Box.test(stresi^2,lag=12,type='Ljung')